// Folder-per-artifact migration integrity: every REAL workstream in this
// repo resolves through the central artifact resolver, no flat-era file
// survives, and the resolver's constants agree with what is actually on
// disk. Read-only against the real repo → parallel pass.

import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  type ArtifactKind,
  SUBJECT_STAGES,
  stageSubject,
} from "../src/lib/engine/artifacts.js";
import { REAL_REPO_ROOT } from "./fixtures/engine-repo.js";

// Both roots, because BOTH hold folder-per-artifact workstreams and the
// migration invariants are about the artifact shape, not about liveness.
// Scanning only `_devx/workstreams/` used to be the same thing; the archival
// made it a subset, and it is now the SMALLER subset — 1 live vs 9 archived.
const SUBJECT_ROOTS = [
  { label: "workstreams", abs: join(REAL_REPO_ROOT, "_devx", "workstreams") },
  { label: "archive", abs: join(REAL_REPO_ROOT, "_devx", "archive") },
] as const;

interface Subject {
  /** Directory name, e.g. `story-graph`. */
  slug: string;
  /** Which root it came from — in the test name, so a failure says where. */
  label: string;
  /** The root it lives under; doubles as `repoRoot` for `stageSubject`. */
  rootAbs: string;
  abs: string;
}

/** Directory entries directly under `rootAbs`. Empty when the root is
 *  absent — the caller asserts on that rather than throwing here, so a moved
 *  root produces a named failure instead of a collection-time crash. */
function subjectsUnder(rootAbs: string, label: string): Subject[] {
  if (!existsSync(rootAbs)) return [];
  return readdirSync(rootAbs)
    .filter((n) => !n.startsWith("."))
    .filter((n) => statSync(join(rootAbs, n)).isDirectory())
    .map((slug) => ({ slug, label, rootAbs, abs: join(rootAbs, slug) }));
}

const subjects: Subject[] = SUBJECT_ROOTS.flatMap((r) =>
  subjectsUnder(r.abs, r.label),
);

/** This repo runs `engine.docs_layout: workstream`, and every assertion below
 *  is about THAT tree — so the layout is pinned here rather than resolved.
 *
 *  Through the map because the `*_REL` constants this file used to read went
 *  module-private at dlr105: privatizing them is exactly what makes
 *  `artifactAbs(wsAbs, "prd/agent.md")` unwritable, and a test that kept a
 *  private spelling alive would be the first caller of the bypass. The map
 *  answers the same question from the outside. */
const subjectAbs = (subject: Subject, kind: ArtifactKind): string =>
  stageSubject(
    "workstream",
    { repoRoot: subject.rootAbs, workstreamRel: subject.slug },
    kind,
  ).abs;

describe("workstream migration integrity (folder-per-artifact)", () => {
  // The vacuous-pass guard. Everything below is generated by looping over
  // `subjects`, so an empty scan silently produces a file with nothing in it
  // — passing by asserting nothing. That is what this defends.
  //
  // Deliberately NOT a count. The assertion here used to be
  // `expect(slugs.length).toBeGreaterThanOrEqual(9)`, correct when 9
  // workstreams lived under `_devx/workstreams/` and wrong the moment the
  // archival moved 8 of them — a literal pinned to a population that then
  // drifted (wsmig1). A floor of 1 would be the same defect with a smaller
  // number. These assert SHAPE: the roots exist, and every directory that is
  // on disk is a subject the loops below will cover.
  it("every subject root exists", () => {
    for (const root of SUBJECT_ROOTS) {
      expect(existsSync(root.abs), `${root.label} root missing: ${root.abs}`).toBe(
        true,
      );
    }
  });

  // fb's invariant, and the one the old floor was actually protecting: the
  // generated test count must not be able to silently SHRINK. The loop below
  // registers three `it()` per subject, so a subject that stops being
  // scanned does not fail — it is never registered, and the suite just
  // reports a smaller number. That is a coverage deletion invisible by
  // construction, which is why a shape-only guard is not enough: "the scan
  // matches what is on disk" stays true while the disk empties.
  //
  // So this floor stays a literal, deliberately. What changes is WHAT it
  // counts: the union of both roots rather than `_devx/workstreams/` alone.
  // Archival moves a workstream between the roots and leaves the union
  // unchanged, so the operation that invalidated the old floor cannot
  // invalidate this one. Only a genuine deletion lowers it — which should be
  // a deliberate act that comes here and says so.
  it("the subject population has not shrunk (generated tests can't vanish)", () => {
    expect(
      subjects.length,
      "a workstream disappeared from BOTH _devx/workstreams/ and " +
        "_devx/archive/. Each subject generates 3 integrity tests, and a " +
        "subject that stops being scanned takes its tests with it silently. " +
        "If the removal was deliberate, lower this floor in the same commit.",
    ).toBeGreaterThanOrEqual(10);
  });

  it("the scan covers every directory present under each root", () => {
    for (const root of SUBJECT_ROOTS) {
      const onDisk = readdirSync(root.abs)
        .filter((n) => !n.startsWith("."))
        .filter((n) => statSync(join(root.abs, n)).isDirectory())
        .sort();
      const scanned = subjects
        .filter((s) => s.label === root.label)
        .map((s) => s.slug)
        .sort();
      expect(scanned, `${root.label}: scan dropped entries`).toEqual(onDisk);
      // Non-empty is the vacuous-pass half. Both roots hold workstreams
      // today; a root that legitimately empties should fail here and be
      // removed from SUBJECT_ROOTS deliberately, not drain unnoticed.
      expect(onDisk.length, `${root.label} is empty`).toBeGreaterThan(0);
    }
  });

  for (const subject of subjects) {
    const { slug, wsAbs } = { slug: subject.slug, wsAbs: subject.abs };

    it(`${subject.label}/${slug}: no flat-era prd.md/design.md/plan.md survives`, () => {
      for (const flat of ["prd.md", "design.md", "plan.md"]) {
        expect(
          existsSync(join(wsAbs, flat)),
          `${slug}/${flat} is flat-era — the engine reads ${flat.replace(".md", "/agent.md")}`,
        ).toBe(false);
      }
    });

    it(`${subject.label}/${slug}: a stage folder with agent-side content carries agent.md`, () => {
      // A stage dir holding ONLY human-side companions is legal — the
      // human can `devx outline init` a stage before the agent authors it
      // (artifacts.ts documents exactly this ordering). What must never
      // exist is agent-side stage content without its agent.md.
      const HUMAN_SIDE = new Set(["outline.md", "outline-critique.md", "human.md"]);
      // Driven by SUBJECT_STAGES rather than a hand-kept triple: a fourth
      // authored stage would otherwise arrive unchecked.
      for (const stage of SUBJECT_STAGES) {
        const stageDir = join(wsAbs, stage);
        if (!existsSync(stageDir)) continue; // stage not reached — legal
        const entries = readdirSync(stageDir).filter((n) => !n.startsWith("."));
        const agentSide = entries.filter((n) => !HUMAN_SIDE.has(n));
        if (agentSide.length === 0) continue; // outline-first — legal
        expect(
          existsSync(subjectAbs(subject, { kind: "agent", stage })),
          `${slug}/${stage}/ holds agent-side files (${agentSide.join(", ")}) without agent.md`,
        ).toBe(true);
      }
    });

    it(`${subject.label}/${slug}: expectations.md stays at the workstream root`, () => {
      expect(existsSync(subjectAbs(subject, { kind: "expectations" }))).toBe(true);
    });
  }
});
